// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClMYIF1dUvkr9Cj0TUuZ6iZ3y76LU9ASw',
    appId: '1:912217498115:web:d2a881bfa72040ba73a436',
    messagingSenderId: '912217498115',
    projectId: 'crud-tutorial-f6147',
    authDomain: 'crud-tutorial-f6147.firebaseapp.com',
    storageBucket: 'crud-tutorial-f6147.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtp0Emt8kt6CkLzID9B83eZhbTR7n7BRk',
    appId: '1:912217498115:android:39439f402bfd1d3e73a436',
    messagingSenderId: '912217498115',
    projectId: 'crud-tutorial-f6147',
    storageBucket: 'crud-tutorial-f6147.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaRgHT0iGMry6Fu4uIDjVY2vDMKSTKU80',
    appId: '1:912217498115:ios:eccdb145f542367573a436',
    messagingSenderId: '912217498115',
    projectId: 'crud-tutorial-f6147',
    storageBucket: 'crud-tutorial-f6147.appspot.com',
    iosBundleId: 'com.example.crudTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaRgHT0iGMry6Fu4uIDjVY2vDMKSTKU80',
    appId: '1:912217498115:ios:4a4f56a93c52250f73a436',
    messagingSenderId: '912217498115',
    projectId: 'crud-tutorial-f6147',
    storageBucket: 'crud-tutorial-f6147.appspot.com',
    iosBundleId: 'com.example.crudTutorial.RunnerTests',
  );
}
